name: TestNuget
on: workflow_dispatch
jobs:
  GoTest:
    runs-on: windows-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: nugetPack
        run: dotnet pack PowerCollections --configuration Release --no-restore
      - name: nugetPublish
        run: nuget push *.nupkg -s "https://nuget.pkg.github.com/OblivionSorcerer/index.json" -k ${{ secrets.GITHUB_TOKEN }}
        
